camera.i_calibration_dump: false
camera.i_enable_diagnostics: true
camera.i_enable_imu: false
camera.i_enable_ir: false
camera.i_enable_sync: true
camera.i_external_calibration_path: ''
camera.i_floodlight_brightness: 0
camera.i_ip: ''
camera.i_laser_dot_brightness: 100
camera.i_mx_id: ''
camera.i_nn_type: none
camera.i_pipeline_dump: false
camera.i_pipeline_type: RGB
camera.i_publish_tf_from_calibration: false
camera.i_restart_on_diagnostics_error: false
camera.i_rs_compat: false
camera.i_tf_base_frame: oak
camera.i_tf_cam_pitch: '0.0'
camera.i_tf_cam_pos_x: '0.0'
camera.i_tf_cam_pos_y: '0.0'
camera.i_tf_cam_pos_z: '0.0'
camera.i_tf_cam_roll: '0.0'
camera.i_tf_cam_yaw: '0.0'
camera.i_tf_camera_model: ''
camera.i_tf_camera_name: oakd
camera.i_tf_custom_urdf_location: ''
camera.i_tf_custom_xacro_args: ''
camera.i_tf_imu_from_descr: 'false'
camera.i_tf_parent_frame: oak-d-base-frame
camera.i_usb_port_id: ''
camera.i_usb_speed: SUPER_PLUS
diagnostic_updater.period: 1.0
diagnostic_updater.use_fqn: false
imu.i_acc_cov: 0.0
imu.i_acc_freq: 400
imu.i_acc_mode: ACCELEROMETER_RAW
imu.i_enable_acc: true
imu.i_enable_gyro: true
imu.i_enable_mag: false
imu.i_enable_rotation: false
imu.i_get_base_device_timestamp: false
imu.i_gyro_cov: 0.0
imu.i_gyro_freq: 400
imu.i_gyro_mode: GYROSCOPE_RAW
imu.i_max_q_size: 8
imu.i_message_type: IMU
imu.i_sync_method: LINEAR_INTERPOLATE_ACCEL
imu.i_update_ros_base_time_on_ros_msg: false
oakd.rgb.preview.image_raw.enable_pub_plugins:
- image_transport/compressedDepth
- image_transport/compressed
- image_transport/raw
- image_transport/theora
oakd.rgb.preview.image_raw.format: jpeg
oakd.rgb.preview.image_raw.jpeg_quality: 95
oakd.rgb.preview.image_raw.png_level: 3
oakd.rgb.preview.image_raw.tiff.res_unit: inch
oakd.rgb.preview.image_raw.tiff.xdpi: -1
oakd.rgb.preview.image_raw.tiff.ydpi: -1
pipeline_gen.i_enable_diagnostics: true
pipeline_gen.i_enable_imu: true
pipeline_gen.i_enable_sync: false
qos_overrides./parameter_events.publisher.depth: 1000
qos_overrides./parameter_events.publisher.durability: volatile
qos_overrides./parameter_events.publisher.history: keep_last
qos_overrides./parameter_events.publisher.reliability: reliable
rgb.i_add_exposure_offset: false
rgb.i_board_socket_id: 0
rgb.i_calibration_file: ''
rgb.i_color_order: BGR
rgb.i_disable_node: false
rgb.i_enable_feature_tracker: false
rgb.i_enable_lazy_publisher: true
rgb.i_enable_nn: false
rgb.i_enable_preview: true
rgb.i_exposure_offset: 0
rgb.i_fps: 30.0
rgb.i_fsync_continuous: false
rgb.i_fsync_trigger: false
rgb.i_get_base_device_timestamp: false
rgb.i_height: 720
rgb.i_interleaved: false
rgb.i_isp_den: 3
rgb.i_isp_num: 2
rgb.i_keep_preview_aspect_ratio: true
rgb.i_low_bandwidth: true
rgb.i_low_bandwidth_bitrate: 0
rgb.i_low_bandwidth_ffmpeg_encoder: libx264
rgb.i_low_bandwidth_frame_freq: 30
rgb.i_low_bandwidth_profile: 4
rgb.i_low_bandwidth_quality: 50
rgb.i_max_q_size: 10
rgb.i_output_isp: true
rgb.i_preview_height: 250
rgb.i_preview_size: 250
rgb.i_preview_width: 250
rgb.i_publish_compressed: false
rgb.i_publish_topic: false
rgb.i_resolution: '1080'
rgb.i_reverse_stereo_socket_order: false
rgb.i_sensor_img_orientation: AUTO
rgb.i_set_isp3a_fps: false
rgb.i_set_isp_scale: true
rgb.i_simulate_from_topic: false
rgb.i_simulated_topic_name: ''
rgb.i_synced: false
rgb.i_update_ros_base_time_on_ros_msg: false
rgb.i_width: 1280
rgb.r_auto_exp_region_height: 0
rgb.r_auto_exp_region_start_x: 0
rgb.r_auto_exp_region_start_y: 0
rgb.r_auto_exp_region_width: 0
rgb.r_auto_exposure_limit: 1000
rgb.r_chroma_denoise: 1
rgb.r_exposure: 20000
rgb.r_focus: 1
rgb.r_iso: 800
rgb.r_luma_denoise: 1
rgb.r_set_auto_exp_region: false
rgb.r_set_auto_exposure_limit: false
rgb.r_set_chroma_denoise: false
rgb.r_set_luma_denoise: false
rgb.r_set_man_exposure: false
rgb.r_set_man_focus: false
rgb.r_set_man_whitebalance: false
rgb.r_set_sharpness: false
rgb.r_sharpness: 1
rgb.r_whitebalance: 3300
use_sim_time: false
